[package]
name = "rustfs-examples"
version = "0.1.0"
authors = ["xxks-kkk <ferrishu3886@gmail.com>"]
edition = "2018"

[dependencies]
rustfs2 = { path="../../rustfs2"}
env_logger = "0.6.0"
bincode = "1.1.3"
serde_derive = "1.0.91"
serde = "1.0.91"