[package]
name = "utils"
version = "0.1.0"
authors = ["xxks-kkk <ferrishu3886@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.6"
env_logger = "0.6.0"
failure = ""
colored = "1.7"
rand = "0.6.4"
hex-literal = "0.1.1"
sha2 = "0.8.0"
